#!/bin/bash

./awk.sh AethionemaArabicum
./awk.sh AlabamaGladecress
./awk.sh AlpineRockcress
./awk.sh Apple
./awk.sh AquilariaAgallochum
./awk.sh ArabidopsisHalleri_subsp_gemmifera
./awk.sh ArabidopsisLyrata_subsp_lyrata
./awk.sh ArabidopsisThaliana
./awk.sh BarrelClover
./awk.sh BetaVulgaris_subsp_vulgaris
./awk.sh BlackCottonwood
./awk.sh BlueLupin
./awk.sh BrassicaOleracea_var_oleracea
./awk.sh Cacao
./awk.sh Camelina
./awk.sh CannabisSativa
./awk.sh Capsella
./awk.sh ChineseChestnut
./awk.sh ChineseWhitePear
./awk.sh Chlamydomonas
./awk.sh Clementine
./awk.sh ClovePink
./awk.sh CoccomyxaSubellipsoidea_C_169
./awk.sh CommonBean
./awk.sh CommonGrapeVine
./awk.sh CorkscrewPlant
./awk.sh Cucumber
./awk.sh CurrantTomato
./awk.sh DatePalm
./awk.sh DesertPoplar
./awk.sh DwarfBirch
./awk.sh Eggplant
./awk.sh EuropeanAsh
./awk.sh EutremaParvulum
./awk.sh FieldMustard
./awk.sh FoxtailMillet
./awk.sh GardenStrawberry
./awk.sh GlycineMax
./awk.sh GlycineSoja
./awk.sh HimalayanStrawberry
./awk.sh HotPepper
./awk.sh JapaneseApricot
./awk.sh JapaneseStrawberry
./awk.sh KiwiFruit
./awk.sh LeersiaPerrieri
./awk.sh LoblollyPine
./awk.sh LondonRocket
./awk.sh Maize
./awk.sh ManchurianWildRice
./awk.sh Monkeyflower
./awk.sh NicotianaSylvestris
./awk.sh NicotianaTomentosiformis
./awk.sh Orange
./awk.sh OryzaBarthii
./awk.sh OryzaBrachyantha
./awk.sh OryzaGlumipatula
./awk.sh OryzaLongistaminata
./awk.sh OryzaMeridionalis
./awk.sh OryzaNivara
./awk.sh OryzaPunctata
./awk.sh OryzaSativa_JaponicaGroup
./awk.sh Papaya
./awk.sh Peach
./awk.sh PhysicNut
./awk.sh PigeonPea
./awk.sh Potato
./awk.sh PurpleFalseBrome
./awk.sh Radish
./awk.sh Rapeseed
./awk.sh RaphanusRaphanistrum_subsp_raphanistrum
./awk.sh RedClover
./awk.sh SacredLotus
./awk.sh SaltwaterCress
./awk.sh Sesame
./awk.sh SolanumArcanum
./awk.sh SolanumHabrochaites
./awk.sh SolanumPennellii
./awk.sh Sorghum
./awk.sh Spikemoss
./awk.sh Spinach
./awk.sh TauschsGoatgrass
./awk.sh Tomato
./awk.sh TreeCotton
./awk.sh VolvoxCarteri_f_nagariensis
./awk.sh WildEinkorn
./awk.sh WoodlandStrawberry

