#!/bin/bash

./awk.sh A_funestus
./awk.sh A_gambiae
./awk.sh Aardvark
./awk.sh AedesAegypti
./awk.sh Alpaca
./awk.sh AmazonMolly
./awk.sh Armadillo
./awk.sh AstatotilapiaBurtoni
./awk.sh Baboon
./awk.sh BactrianCamel
./awk.sh Baiji
./awk.sh BigBrownBat
./awk.sh Bison
./awk.sh BlackFlyingFox
./awk.sh BlindMolerat
./awk.sh Bonobo
./awk.sh BrandtsBat
./awk.sh BrazilianGuineaPig
./awk.sh Bushbaby
./awk.sh C_brenneri
./awk.sh CapeElephantShrew
./awk.sh CapeGoldenMole
./awk.sh Cat
./awk.sh Chimp
./awk.sh Chinchilla
./awk.sh ChineseHamster
./awk.sh ChinesePangolin
./awk.sh ChineseTreeShrew
./awk.sh CionaSavignyi
./awk.sh CommonShrew
./awk.sh Cow
./awk.sh CrabeatingMacaque
./awk.sh DamaralandMolerat
./awk.sh DeerMouse
./awk.sh Degu
./awk.sh Dog
./awk.sh Dolphin
./awk.sh Dromedary
./awk.sh Elephant
./awk.sh Ferret
./awk.sh FlyingLemur
./awk.sh Gibbon
./awk.sh Goat
./awk.sh Gorilla
./awk.sh GreenMonkey
./awk.sh GuineaPig
./awk.sh Hedgehog
./awk.sh Horse
./awk.sh KangarooRat
./awk.sh KillerWhale
./awk.sh KingCobra
./awk.sh LesserEgyptianJerboa
./awk.sh Lizard
./awk.sh Manatee
./awk.sh Marmoset
./awk.sh Megabat
./awk.sh Microbat
./awk.sh MiniPig
./awk.sh MinkeWhale
./awk.sh MongolianHorse
./awk.sh MouseLemur
./awk.sh Mouse
./awk.sh NakedMolerat
./awk.sh Opossum
./awk.sh Panda
./awk.sh Pig
./awk.sh Platypus
./awk.sh PolarBear
./awk.sh PrairieVole
./awk.sh ProboscisMonkey
./awk.sh PrzewalskiHorse
./awk.sh Rabbit
./awk.sh Rat
./awk.sh Rhesus
./awk.sh RockHyrax
./awk.sh Sheep
./awk.sh SiberianTiger
./awk.sh Sloth
./awk.sh SnubnosedMonkey
./awk.sh SouthernHouseMosquito
./awk.sh SpermWhale
./awk.sh SquirrelMonkey
./awk.sh StarletSeaAnemone
./awk.sh SumatranOrangutan
./awk.sh Tarsier
./awk.sh TasDevil
./awk.sh Tenrec
./awk.sh TibetanAntelope
./awk.sh TibetanPig
./awk.sh TreeShrew
./awk.sh Viper
./awk.sh Wallaby
./awk.sh Walrus
./awk.sh WaterBuffalo
./awk.sh WeddellSeal
./awk.sh WesternClawedFrog
./awk.sh WhiteRhino
./awk.sh WildSheep
./awk.sh WireWorm
./awk.sh Yak
./awk.sh ZebraMbuna
./awk.sh Zebu
./awk.sh hg19

