./domains.sh AethionemaArabicum
./domains.sh AlabamaGladecress
./domains.sh AlpineRockcress
./domains.sh Apple
./domains.sh AquilariaAgallochum
./domains.sh ArabidopsisHalleri_subsp_gemmifera
./domains.sh ArabidopsisLyrata_subsp_lyrata
./domains.sh ArabidopsisThaliana
./domains.sh BarrelClover
./domains.sh BetaVulgaris_subsp_vulgaris
./domains.sh BlackCottonwood
./domains.sh BlueLupin
./domains.sh BrassicaOleracea_var_oleracea
./domains.sh Cacao
./domains.sh Camelina
./domains.sh CannabisSativa
./domains.sh Capsella
./domains.sh ChineseChestnut
./domains.sh ChineseWhitePear
./domains.sh Chlamydomonas
./domains.sh Clementine
./domains.sh ClovePink
./domains.sh CoccomyxaSubellipsoidea_C_./domains.sh69
./domains.sh CommonBean
./domains.sh CommonGrapeVine
./domains.sh CorkscrewPlant
./domains.sh Cucumber
./domains.sh CurrantTomato
./domains.sh DatePalm
./domains.sh DesertPoplar
./domains.sh DwarfBirch
./domains.sh Eggplant
./domains.sh EuropeanAsh
./domains.sh EutremaParvulum
./domains.sh FieldMustard
./domains.sh FoxtailMillet
./domains.sh GardenStrawberry
./domains.sh GlycineMax
./domains.sh GlycineSoja
./domains.sh HimalayanStrawberry
./domains.sh HotPepper
./domains.sh JapaneseApricot
./domains.sh JapaneseStrawberry
./domains.sh KiwiFruit
./domains.sh LeersiaPerrieri
./domains.sh LoblollyPine
./domains.sh LondonRocket
./domains.sh Maize
./domains.sh ManchurianWildRice
./domains.sh Monkeyflower
./domains.sh NicotianaSylvestris
./domains.sh NicotianaTomentosiformis
./domains.sh Orange
./domains.sh OryzaBarthii
./domains.sh OryzaBrachyantha
./domains.sh OryzaGlumipatula
./domains.sh OryzaLongistaminata
./domains.sh OryzaMeridionalis
./domains.sh OryzaNivara
./domains.sh OryzaPunctata
./domains.sh OryzaSativa_JaponicaGroup
./domains.sh Papaya
./domains.sh Peach
./domains.sh PhysicNut
./domains.sh PigeonPea
./domains.sh Potato
./domains.sh PurpleFalseBrome
./domains.sh Radish
./domains.sh Rapeseed
./domains.sh RaphanusRaphanistrum_subsp_raphanistrum
./domains.sh RedClover
./domains.sh SacredLotus
./domains.sh SaltwaterCress
./domains.sh Sesame
./domains.sh SolanumArcanum
./domains.sh SolanumHabrochaites
./domains.sh SolanumPennellii
./domains.sh Sorghum
./domains.sh Spikemoss
./domains.sh Spinach
./domains.sh TauschsGoatgrass
./domains.sh Tomato
./domains.sh TreeCotton
./domains.sh VolvoxCarteri_f_nagariensis
./domains.sh WildEinkorn
./domains.sh WoodlandStrawberry