#!/bin/bash

./separate.sh AethionemaArabicum
./separate.sh AlabamaGladecress
./separate.sh AlpineRockcress
./separate.sh Apple
./separate.sh AquilariaAgallochum
./separate.sh ArabidopsisHalleri_subsp_gemmifera
./separate.sh ArabidopsisLyrata_subsp_lyrata
./separate.sh ArabidopsisThaliana
./separate.sh BarrelClover
./separate.sh BetaVulgaris_subsp_vulgaris
./separate.sh BlackCottonwood
./separate.sh BlueLupin
./separate.sh BrassicaOleracea_var_oleracea
./separate.sh Cacao
./separate.sh Camelina
./separate.sh CannabisSativa
./separate.sh Capsella
./separate.sh ChineseChestnut
./separate.sh ChineseWhitePear
./separate.sh Chlamydomonas
./separate.sh Clementine
./separate.sh ClovePink
./separate.sh CoccomyxaSubellipsoidea_C_169
./separate.sh CommonBean
./separate.sh CommonGrapeVine
./separate.sh CorkscrewPlant
./separate.sh Cucumber
./separate.sh CurrantTomato
./separate.sh DatePalm
./separate.sh DesertPoplar
./separate.sh DwarfBirch
./separate.sh Eggplant
./separate.sh EuropeanAsh
./separate.sh EutremaParvulum
./separate.sh FieldMustard
./separate.sh FoxtailMillet
./separate.sh GardenStrawberry
./separate.sh GlycineMax
./separate.sh GlycineSoja
./separate.sh HimalayanStrawberry
./separate.sh HotPepper
./separate.sh JapaneseApricot
./separate.sh JapaneseStrawberry
./separate.sh KiwiFruit
./separate.sh LeersiaPerrieri
./separate.sh LoblollyPine
./separate.sh LondonRocket
./separate.sh Maize
./separate.sh ManchurianWildRice
./separate.sh Monkeyflower
./separate.sh NicotianaSylvestris
./separate.sh NicotianaTomentosiformis
./separate.sh Orange
./separate.sh OryzaBarthii
./separate.sh OryzaBrachyantha
./separate.sh OryzaGlumipatula
./separate.sh OryzaLongistaminata
./separate.sh OryzaMeridionalis
./separate.sh OryzaNivara
./separate.sh OryzaPunctata
./separate.sh OryzaSativa_JaponicaGroup
./separate.sh Papaya
./separate.sh Peach
./separate.sh PhysicNut
./separate.sh PigeonPea
./separate.sh Potato
./separate.sh PurpleFalseBrome
./separate.sh Radish
./separate.sh Rapeseed
./separate.sh RaphanusRaphanistrum_subsp_raphanistrum
./separate.sh RedClover
./separate.sh SacredLotus
./separate.sh SaltwaterCress
./separate.sh Sesame
./separate.sh SolanumArcanum
./separate.sh SolanumHabrochaites
./separate.sh SolanumPennellii
./separate.sh Sorghum
./separate.sh Spikemoss
./separate.sh Spinach
./separate.sh TauschsGoatgrass
./separate.sh Tomato
./separate.sh TreeCotton
./separate.sh VolvoxCarteri_f_nagariensis
./separate.sh WildEinkorn
./separate.sh WoodlandStrawberry

