#!/bin/bash

./separate.sh A_funestus
./separate.sh A_gambiae
./separate.sh Aardvark
./separate.sh AcornWorm
./separate.sh Acul
./separate.sh AedesAegypti
./separate.sh Aepiro
./separate.sh Alpaca
./separate.sh AmazonMolly
./separate.sh Armadillo
./separate.sh Asinensis
./separate.sh AstatotilapiaBurtoni
./separate.sh Asteph
./separate.sh Baboon
./separate.sh BactrianCamel
./separate.sh Baiji
./separate.sh BigBrownBat
./separate.sh Bison
./separate.sh BlackFlyingFox
./separate.sh BlindMolerat
./separate.sh Bonobo
./separate.sh BrandtsBat
./separate.sh BrazilianGuineaPig
./separate.sh Bushbaby
./separate.sh C_brenneri
./separate.sh CapeElephantShrew
./separate.sh CapeGoldenMole
./separate.sh Cat
./separate.sh Chimp
./separate.sh Chinchilla
./separate.sh ChineseHamster
./separate.sh ChineseLiverFluke
./separate.sh ChinesePangolin
./separate.sh ChineseTreeShrew
./separate.sh CionaSavignyi
./separate.sh CommonShrew
./separate.sh Cow
./separate.sh CrabeatingMacaque
./separate.sh DamaralandMolerat
./separate.sh DeerMouse
./separate.sh Degu
./separate.sh Dog
./separate.sh Dolphin
./separate.sh Dromedary
./separate.sh Elephant
./separate.sh Ferret
./separate.sh FlyingLemur
./separate.sh Gibbon
./separate.sh Goat
./separate.sh Gorilla
./separate.sh GreenMonkey
./separate.sh GuineaPig
./separate.sh Hedgehog
./separate.sh Horse
./separate.sh KangarooRat
./separate.sh KillerWhale
./separate.sh KingCobra
./separate.sh LesserEgyptianJerboa
./separate.sh Lizard
./separate.sh Manatee
./separate.sh Marmoset
./separate.sh Megabat
./separate.sh Microbat
./separate.sh MiniPig
./separate.sh MinkeWhale
./separate.sh MongolianHorse
./separate.sh MouseLemur
./separate.sh Mouse
./separate.sh NakedMolerat
./separate.sh NeolamprologusBrichardi
./separate.sh NileTilapia
./separate.sh Opossum
./separate.sh Panda
./separate.sh Pig
./separate.sh Platypus
./separate.sh PolarBear
./separate.sh PrairieVole
./separate.sh ProboscisMonkey
./separate.sh PrzewalskiHorse
./separate.sh Rabbit
./separate.sh Rat
./separate.sh Rhesus
./separate.sh RockHyrax
./separate.sh Sheep
./separate.sh SiberianTiger
./separate.sh Sloth
./separate.sh SnubnosedMonkey
./separate.sh SouthernHouseMosquito
./separate.sh SpermWhale
./separate.sh SquirrelMonkey
./separate.sh StarletSeaAnemone
./separate.sh SumatranOrangutan
./separate.sh Tarsier
./separate.sh TasDevil
./separate.sh Tenrec
./separate.sh TibetanAntelope
./separate.sh TibetanPig
./separate.sh TreeShrew
./separate.sh Viper
./separate.sh Wallaby
./separate.sh Walrus
./separate.sh WaterBuffalo
./separate.sh WeddellSeal
./separate.sh WesternClawedFrog
./separate.sh WhiteRhino
./separate.sh WildSheep
./separate.sh WireWorm
./separate.sh Yak
./separate.sh ZebraMbuna
./separate.sh Zebrafish
./separate.sh Zebu
./separate.sh hg19



